### ISSUE TITLE
Change dark gtk titlebar?

### ISSUE THREAD

**Issue by Hedronmx** [vjba/whatstron#5]
Is it possible to change the titlebar to default color?

I am running elementary os and its opening to the dark variant

**Comment by vjba** [comment]
Hi @Hedronmx and thank you for your feature request. 

This is a great idea. I'll implement a persistent option for users to choose the titlebar colour. I'll also do some digging around to see if electron can inherit the GTK default to save the need to change the colour in the first place.

**Comment by vjba** [comment]
Turns out Electron inherits the GTK theme by itself anyway, @Hedronmx. New release has been published [here](https://github.com/vjba/whatstron/releases/tag/1.1.2).

**Comment by Hedronmx** [comment]
Thanks man! that was fast.
